---
- name: Install haproxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Configure haproxy for Kubernetes API
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy

