---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - software-properties-common
    state: present

- name: Disable swap (runtime)
  command: swapoff -a
  when: ansible_swaptotal_mb | int > 0

- name: Disable swap (persist)
  replace:
    path: /etc/fstab
    regexp: '^\s*([^#]\S*\s+)\S+\s+swap\s+'
    replace: '# \1 none swap '

- name: Kernel modules file
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Load kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter
  args:
    warn: false

- name: Sysctl for Kubernetes
  copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1

- name: Apply sysctl
  command: sysctl --system

# --- containerd ---
- name: Install containerd
  apt:
    name: containerd
    state: present

- name: Ensure /etc/containerd
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate default containerd config
  command: containerd config default
  register: containerd_default_cfg
  changed_when: false

- name: Write containerd config with systemd cgroup
  copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_default_cfg.stdout | regex_replace('SystemdCgroup = false','SystemdCgroup = true') }}"
  notify: Restart containerd

- name: Enable/start containerd
  systemd:
    name: containerd
    enabled: true
    state: started

# --- Kubernetes packages ---
- name: Add Kubernetes apt keyring
  shell: |
    set -e
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key \
      | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    chmod 0644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repo
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /
  notify: Apt update

- name: Install kubeadm, kubelet, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: true
    state: started


