---
- name: Wait for CoreDNS to be running
  shell: "kubectl --kubeconfig=/etc/kubernetes/admin.conf get pods -A -o json"
  register: pods_json
  until: >
    (pods_json.stdout | from_json).items |
    selectattr('metadata.namespace','equalto','kube-system') |
    selectattr('metadata.labels.k8s-app','defined') |
    selectattr('metadata.labels.k8s-app','equalto','kube-dns') |
    map(attribute='status.phase') | list | select('equalto','Running') | length >= 2
  retries: 30
  delay: 10

- name: Wait until all nodes are Ready
  vars:
    expected_nodes: "{{ groups['control_plane'] | length + groups['workers'] | length }}"
  shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf get nodes -o json
  register: nodes_json
  until: >
    ((nodes_json.stdout | from_json).items | length) == expected_nodes and
    (((nodes_json.stdout | from_json).items |
      map(attribute='status.conditions') | list) |
      map('selectattr','type','equalto','Ready') |
      map('selectattr','status','equalto','True') | list | length) == expected_nodes
  retries: 60
  delay: 10

- name: Print node list
  shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf get nodes -o wide
  register: nodes_out

- debug:
    msg: "{{ nodes_out.stdout_lines }}"

